braintreeps/vim_dotfiles

vim/after/plugin/netrw_list_hide.vim

Currently the only way to navigate up when browsing is by hitting `-`, this commit prevents the `..` entry from being hidden from directory listings.
This change isn't made to vimrc because `g:netrw_list_hide` is mangled by [vinegar](https://github.com/braintreeps/vim_dotfiles/tree/master/vim/bundle/vim-vinegar) and must be changed after the plugins have finished running.

netrw shouldn't hide parent directory

---

vimrc

Worked on this with @tlrobrn. We used @ideal-knee's grep regex magic.
Running `<leader>ds` (describe spec) should output this for the spec you are currently on:
Works for RSpec and Mocha files.

Add vimux command to describe current spec

---

vimrc

By default, vim-markdown does a lot of folding on markdown files. 
Per [this section of the vim-markdown repo](https://github.com/plasticboy/vim-markdown#disable-folding), that can be easily disabled.
For markdown heavy repos, this is a must.

Add line to prevent folding in markdown files

---

vimrc.bundles

Now bufexplorer points here: https://github.com/braintreeps/bufexplorer
Which is the working version of buffer explorer in Drew's dotfiles.

Pin bufexplorer to working version on braintreeps repo

---

vimrc

Previously running <leader>cw would move you to the bottom of the file after running. This change should keep your cursor where it was previously positioned.

Update trim to stay on same line after substitution

---

vimrc

I often want to open files in `node_modules` or `bower_components` (to hack on or inspect); since we use `wildignore` to remove those files from CommandT,  we miss out on path completion and other niceties. Using [`CommandTWildIgnore`](https://github.com/wincent/command-t/blob/master/doc/command-t.txt#L779) allows the best of both worlds.

Move vendor ignores from wildignore to command_t ignore

---

vimrc
vimrc.bundles

Remove deprecated VimClojure, add vim-clojure-highlight and rainbow_parentheses.vim.
This is an attempt to get the common Vim config to a decent place to edit Clojure.  It is targeted at folks that are ~new to Clojure/don't have strong enough opinions on how they want to have their editor configured (yet.)  Some tools that I'm on the fence about adding:
* [paredit](https://github.com/vim-scripts/paredit.vim)/[vim-sexp](https://github.com/tpope/vim-sexp-mappings-for-regular-people) (for easier/more structured Lisp editing)
* [salve.vim](https://github.com/tpope/vim-salve) (integrate repl/test/build into Vim)
* [vim-cljfmt](https://github.com/venantius/vim-cljfmt) (formatting)
I also plan to write up a quick start for using these plugins.
Any feedback would be appreciated.

Update Clojure stuff

---

vimrc

Add an EOL match for ignore rules so files like ‘Checkout.class.php’
don’t get ignored while ‘JavaBeanFactory.class’ is ignored as intended.

Stricter regexen for NERDTreeIgnore

---

vim/colors/vibrantink.vim

An upgrade of command-t caused it to use `PmenuSel` for the selected file foreground and background. The current combo of `ctermfg=0` and `ctermbg=242` makes the text invisible in iTerm (or at least my terminal). Changing it so `ctermfg=NONE` mimics the previous behavior when command-t used `Visual` for the highlighting.

Change PmenuSel foreground to NONE to fix iTerm visibility

---

vimrc
vimrc.bundles

As best I can tell, vim-puppet is a fork of vim-puppet-syntax that is
more actively maintained. Switching means we don't need to have our own
fork of vim-puppet-syntax anymore (it added the unless keyword in too),
and gives us the ability to turn automatic alignment in hashes on and
off, instead of forcing it on (see the one change to vimrc).

Switch to vim-puppet instead of vim-puppet-syntax.

---

vimrc

To avoid changing the behavior when opening files, this includes an `autocmd` to force all folds fully open.

Update vimrc to set foldmethod to indent

---

vimrc
vimrc.bundles

This plugin allows for the following functionality:
1. <leader\>ss will open up every instance of the word under the cursor in a side panel
2. :SS <word to search\> will open up any instance of the specified word
3. Scrolling between instances of that word within files and in-between files is super easy (with n for next and N for  #previous)
4. Seeing the context around the instances of that word is very helpful
Please view gif below:

Add side-search plugin

---

vimrc

This change makes the vim tabline more useful looking -- it shows tab number for easier navigation and removes a lot of cruftiness that sometimes crops up near the filename.
I know nobody here really uses vim tabs, but it would be nice to have.

prettify vim tabline

---

vimrc

Vim's default saving behavior writes a new file, which breaks the bind mount
for any top level files (this is unlike directory-mounting behavior, since
directories are aware of file inodes). Setting backupcopy allows for
changes to top level files on the host to propagate to the container.

Set backupcopy for top-level file mounting in Docker

---

vimrc

The trailing whitespace is removed anyway on save, and seeing red
whenever you press `<space>` is jarring.

Do not highlight trailing whitespace

---

vimrc.bundles

[tpope/vim-unimpaired](https://github.com/tpope/vim-unimpaired) Adds a number of handy mappings.
Some highlights
- `]q`, `[q` for navigating the quickfix list
- `]<Space>`, `[<Space>` for inserting lines without leaving normal mode
- `]f`, `[f` for switching to the next/previous file
As far as I've seen, there aren't any conflicts

Add unimpaired.vim

---

vimrc.bundles

Both of these plugins support Vim8 and Neovim and will not block the UI while the are doing their work. I have enabled them only if Vim8 or Neovim is detected.
This PR makes use of [w0rp/ale](https://github.com/w0rp/ale) for non-blocking linting of the current file. It has out-of-the-box support for many linting systems.
For instance, in Python it will automatically use `flake8` in the current virtualenv to lint the current buffer and add mark the lines that need attention.
This PR makes use of [completor.vim](https://github.com/maralla/completor.vim) for as-you-type completion suggestions.
For instance, in a Python project if you have `jedi` installed in the current virtualenv it will automatically supply completion suggestions for library method calls, classes, etc.

Adds async linting and completion choices

---

vimrc

Based on conversations in [braintreeps/vim_dotfiles#56](https://github.com/braintreeps/vim_dotfiles/pull/56), we're thinking the addition of these two options makes for a nice compromise as opposed to completely getting rid of [w0rp/ale](https://github.com/w0rp/ale).
What this change effectively means is "only lint in normal mode and always lint when exiting insert mode".  The net effect is you don't get the weird linting-while-typing behavior.

Add configuration for async linting

---

vimrc
vimrc.bundles

#Until a more non-invasive configuration can be decided on, we are disabling automatic suggestion presentation in this plugin.
See #57 #56 #51

Disable completor.vim automatic suggestions

---

vim/colors/vibrantink.vim
vimrc

This prevents it from opening and closing when w0rp/ale linting finds errors.
Here's a gif showing the old behavior:
And the new behavior:

Keep the signcolumn always open and make it the background color

---

vimrc

Previously, we would ignore anything with the characters `_build` which
would includer things like `view_builders`. This commit explicitly sets
the ignored sections to be folders, not just file names.

Specifically ignore folders for fzf

---

vimrc

As it stands right now, the hashicorp terraform plugin will mangle our tfvars files, it alphabetizes them and adds newlines after each variable definition.  That's all fine and great, but it makes logical visual separation like very difficult.  For example, you can't do:
```
zookeeper_instance_count = 1
kafka_instance_count = 1
cassandra_instance_count = 1
cassandra_baz_count = 2
```

Do not run terraform fmt on .tfvars files

---

vimrc

The consensus seems to be that people dislike the linting so this commit disables it by default.  I left the ALE plugin installed so anyone who wants it can either run `:ALEEnable` or set `g:ale_enabled` to 1 in their .vimrc_local

Disable linting by default

---

vimrc

This adds an additional binding for splitting from the FZF finder ala ctrl-p (`<Ctrl-x>` will still work). I'm also a fan of this because `s for split` is an easier mnemonic device, but that's rather subjective ;)
FZF doesn't [merge `g:fzf_action` with its defaults](https://github.com/junegunn/fzf.vim/blob/master/autoload/fzf/vim.vim#L330), so we need to specify the entire mapping here instead of just specifying one of them :\

FZF: Add an additional split binding to mimic ctrlp

---

vimrc

Something changed recently that causes autocomplete to be really slow
initially as it says its "Scanning tags...". It's hard to say why this
suddenly started happening because it looks like it's default behavior
for vim to look at tags for autocomplete. This change fixes it by
explicitly removing tags from the autocomplete suggestions.

Don't use tags for autocomplete

---

vimrc

This behavior I find more frustrating than useful:
- We already highlight trailing whitespace
- New users are not aware this change is being made when the save
- With this config in place it is difficult to keep whitespace when you
want it, e.g. trying to make a minimal diff that does not introduce
extraneous changes.

Stop clearing trailing whitespace when saving

---

vimrc.bundles

This plugin adds Ruby's block as a text object, allowing you to
manipulate ruby blocks like you can with ruby methods. For example,
`yir` (yank-inner-ruby) will yank the contents of a block while `dar`
(delete-all-ruby) will delete the whole block.
See https://github.com/nelstrom/vim-textobj-rubyblock for more
information and examples.
(the textobj-user plugin is a dependency of vim-textobj-rubyblock)

Add vim-textobj-rubyblock plugin

---

vimrc

This colorscheme switching breaks highlighting of trailing whitespace.
This change does make diffs in vim look worse, but it mostly fixes
whitespace highlighting.
There is still an issue where highlithing is removed on the new window
when a file is split. It still remains in the original window, however.

Do not switch colorschemes for diffs

---

vim/colors/vibrantink.vim

This gives the diff output proper color.  Adapted from tpope's vividchalk at https://github.com/tpope/vim-vividchalk/blob/master/colors/vividchalk.vim.
Screenshot: ![Diff highlighting](https://dl.dropbox.com/s/6twl43aftsibx95/Screenshot%202017-09-25%2014.17.23.png?dl=0)

Improve vibrant ink diff syntax highlighting

---

vimrc

For those of us who use a dark colorscheme for their terminal, the
current 'black' background highlight for long lines is invisible. I
didn't actually realise we had *any* highlighting of long lines until I
investigated adding it and discovered this configuration.
This gives long lines (> 125 chars) a 'red' background, just as we do
for trailing whitespace. It appears this was the initial configuration
when [line length highlighting was added][1] back in 2010. However,
shortly after, the background was changed [from red to black][2], as it
is today. It's not clear why that change was made and whether terminals
with black backgrounds were considered. If anybody has any context on
this – and a long memory – please chime in!
Before:
After:
[1]: …

Give long lines a red background highlight

---

vimrc

Reverts braintreeps/vim_dotfiles#78
Unfortunately, this can cause a bit of eye-bleeding for files/projects with a large amount of very long lines.

Revert "Give long lines a red background highlight"

---

vimrc
vimrc.bundles

Rather than the default "hanging" indentation style:
``` ruby
something = if condition
else
end
```
Newer versions of vim-ruby allow the awkwardly named "variable" indentation, which is more inline with our style:
``` ruby
something = if condition
else
end
```

Update vim-ruby and use "variable" assignment indentation

---

vimrc

It seems with a vim upgrade or something else, mouse mode is sometimes start by default, `set ttymouse=` will turn it off in the cases where `set mouse=` is ignored.

Turn off both types of mouse mode.

---

vim/ruby_mappings.vim

Since I don't think ruby-debug is very useful anymore, how about remapping this to pry?

Use pry rather than ruby-debug for LocalLeader rd

---

vimrc
vimrc.bundles

We've recently had some issues where completor is triggering for developers who do not use the plugin. I am similarly in the camp where I do not use or want to use completor. 
Because of this current problem and similar issues with configuration, I'd like to propose we move towards a pattern where enhancements like this are pushed into `~/.vimrc.bundles.local` and  `~/.vimrc_local`. That way teams who regularly use these can maintain their own dotfile customizations (which currently works in all development environments) without needing to worry about affecting anyone else.
If there's a strong case for moving or keeping something in the core I think it's totally acceptable to do so but i'd prefer to keep the core vimrc as trim and generally useful as possible. This gives us the freedom to …

Remove completor from core vim config

---

vimrc

We moved the build_intellij directory into /tmp, so we no longer need to exclude it.

Remove build_intellij from FZF exclusions

---

vimrc

Prints the Git Web URL for the current file at the current selection.
- Parses and constructs the remote Git URL
- Links to either the current line or a range with the current selection
- Uses `echomsg` to save the URL in the message-history
I have a common workflow where I'm investigating something in vim and then I want to send a link of what I'm looking at to someone. 
This change lets me run `:GitWebURL`, copy the URL, and then send it to someone (e.g. via slack). I can also cmd+click the URL which will open it in my browser.
I opted not to make a leader command for it since I'm not sure if it's useful to others. I also opted not to make it a plugin since it was easier to iterate in the vimrc. We can always extract it later if desired.
I don't think this change is impactful enough to …

Add a command to show the URL for the current file in Git

---

vim/ruby_mappings.vim

Add the ability to run `\rc` to run tests for a context.
The move to vim-test would remove the ability to run a test for a
context, this adds that back in. If run on a line that is a context
block, it will run that context as per the previous behavior.
The regexes used here are based on the ones used in `vim-ruby` to find
nested 'class/module/do' + end blocks and navigate them properly. This
will find each parent block until it finds a test context or cannot find
a new parent.
Additionally, the `wall` function was moved inside the function because
on blank lines the `<CR>` would move down a line and that would change
the behavior.

Add function for testing context

---

vimrc
vimrc.bundles

Switch to extracted [vim-github-url](https://github.com/pgr0ss/vim-github-url) plugin.
GitHubURL has been extracted into a standalone plugin and improved.
For example, it now works with unpushed branches and random checked out commits: https://github.com/pgr0ss/vim-github-url/commit/1676bd367b55f2d4a90b0ca62fa674d32adae191

Switch to extracted vim-github-url plugin

---

vimrc.bundles

Signed-off-by: Clayton Liggitt <clayton.liggitt@getbraintree.com>
Fixes `vim-ruby` to the most recent sha where syntax highlighting works. When tpope fixes it, we can start following master or take the newest tag.
There were a [few commits](https://github.com/vim-ruby/vim-ruby/compare/84565856e6965144e1c34105e03a7a7e87401acb...8e9a78106681319b096bdc935eaeca308683bc10) working on this from 2017.
Ruby syntax highlighting for heredocs (specifically in gateway specs) has been broken on cpairs for a while.

peg vim-ruby to the latest sha with unbroken syntax highlighting

---

vimrc

Pressing `*` while highlighting will start searching for the (escaped) highlighted text:

Add a visual mode equivalent to `*` searching

---

vimrc.bundles

Includes [vim-graphql](https://github.com/jparise/vim-graphql) in the plugin bundles.
Currently, GraphQL schema files `.graphql`, `.graphqls` etc. are being treated as `conf` files. This change will allow us to edit schema files in a valid mode.

Include vim-graphql for editing GraphQL schema files.

---

vimrc

Use the `function!` syntax when defining `MyTabLine` and `MyTabLabel`
`function <name>` will raise an error if the function already exists, but `function! <name>` will silently replace it. This allows me to `source $MYVIMRC` without having errors and without having to restart vim. Most of our functions are defined that way, so this is just keeping it consistent in addition to fixing the minor annoyance.
No RFC needed, this is minor change with no impact for most users.

Use the function! syntax for defining MyTabLine and MyTabLabel

---

vimrc

Allows `:A` and `:R` to work with files in `app/lib`.
Currently, `spec/lib/foo_spec.rb` can alternate to `app/lib/foo.rb`, but not vice versa.

Add app/lib to rails_projections

---

vimrc.bundles

What
===
Add maralla completor.
Why
===
It is a really decent autocomplete plugin for go specifically, as it
uses gocode behind the scenes to find meaningful references to complete
on.
Notes
===
The plugin is only enabled when go files are loaded.
Checklist
===

Add maralla completor for go

---

vimrc

Change VimuxRunLastCommand from `\rl `to `\vl`
- This better aligns with other Vimux mappings that start with V
- This prevents it from colliding with the ruby override that changes `\rl`
to TestLast:
https://github.com/braintreeps/vim_dotfiles/blob/c0036eb49cc1933410d0fba8fb125b075b5b0fc9/vim/ruby_mappings.vim#L14-L14

Change VimuxRunLastCommand from \rl to \vl

---

vimrc.bundles

Adds a [syntax highlighting plugin](https://github.com/mxw/vim-jsx) for JSX. Note that this plugin is explicitly compatible with the JS syntax [highlighting plugin](https://github.com/pangloss/vim-javascript) already in use in this repo.
JSX highlighting is currently very much broken in ways described in [this Github issue](https://github.com/pangloss/vim-javascript/issues/242).

Add syntax highlighting plugin for JSX

---

vimrc
vimrc.bundles

This PR makes it possible to format Bazel files using `buildifier` (https://github.com/bazelbuild/buildtools/tree/master/buildifier)
- Currently Bazel files are formatted using the plugin davidzchen/vim-bazel which is [deprecated](https://github.com/davidzchen/vim-bazel#vim-bazel-deprecated-please-use-googlevim-ft-bzl-instead).
- The plugin, while it was in use formatted files in an arbitrary, but consistent format.
- We intend to move to formatting Bazel files using Buildifier.

Add codefmt to format Bazel files using Buildifer.

---

vim/ruby_mappings.vim

Remove references to Inferior Slime.
Inferior Slime is a deprecated internal tool.

Remove references to inferior slime

---

vimrc

Add .github files to FZF fuzzy finder
It's nice to be able to fuzzy find PULL_REQUEST_TEMPLATE, CODEOWNERS, etc.

Add .github files to FZF fuzzy finder

---

vimrc

Ignore the `tmp` directory in nerdtree.
Use `find .` in fzf to search for all files, including hiddine ones. It
will ignore the .git directory (as well as tmp) and it uses a sed to
remove the leading `./` from the results so it looks the same as
`find *`.
We shouldn't need to navigate to the `tmp` folder usually, and if we do,
needing to do it via fzf clutters all of the fzf results.
Also, it can often be useful to find hidden files in fzf like
.rubocop or .rspec or similar other config files. By using `find *`
instead of `find .` we eliminate this. Additionally, `find *` can have
some weirdness depending on file names.

Ignore tmp, and fzf for hidden files

---

vimrc
vimrc.bundles

Using `git ls-files` via `fzf#vim#gitfiles` is better because it will
respect the gitignore. However, we are not always in a gitrepo so we
need to check for that.
Additionally, this will ignore the vendor repo, because while it may be
not ignored, we don't really want to be fzf-ing through it.

Use GFiles for fzf when possible

---

autoload/test/java/bazeltest.vim
java_mappings.vim
vimrc

Add vim-test custom runner for java projects using bazel that runs the
test underneath the cursor, or all the tests in the current buffers
class.
To make running java tests when in vim easier.
- The runner uses bazel query to dig up the appropriate target for the
file that is open. At the moment it requires 3 separate calls to bazel,
and I'm looking into how to reduce that to 1.
- The runner pipes the results of bazel commands stderr to /dev/null
because bazel does not support anyway of turning off INFO and DEBUG
error logs yet.

Add vim-test custom runner for java projects using bazel

---

vimrc
vimrc.bundles

Remove unused imports in Java files when saving the file.
To keep the list of imports relevant to the code in the file, and to
align with our IntelliJ config.

Remove unused imports in Java files

---

after/indent/java.vim
vimrc

Make our vim java indents more consistent with IntelliJ by:
- `tabstop=2 shiftwidth=2 softtabstop=2`: tabs are 2 spaces
- `cinoptions` `+1s`: continuation indents are 1x shiftwidth (i.e. 2 spaces)
- `cinoptions` `(0`: continuation indents in function argument lists align on new lines
- `cinoptions` `W1s`: continuation indents in function argument where the
first item is on the next line fallback to standard continuation
indenting
Writing java in our vim config is significantly different to our
IntelliJ config. These changes make some basic improvements, more are
needed, but this makes vim do the right thing in many more cases than
it does now.

Make our vim java indents more consistent with IntelliJ

---

autoload/test/java/bazeltest.vim

Support multiple targets when running bazel tests by running the test on
any target that the test is executable within.
A test file can exist in multiple targets. If that's the case bazel
query returns the list of targets new line separated. We can pass
multiple targets to bazel test and it will run the test once for each
target. Without this change the command has a new line in it and it runs
the tests for the suite and then outputs other stuff into the terminal.

Support multiple targets when running bazel tests

---

vimrc
vimrc.bundles

Add vim-yaml-helper plugin and configure it to display in the status
line the full path to the key under the cursor.
Looking at really large YAML files it can be difficult to see what the
root node or full path is without doing a lot of scrolling. This helps
us navigate large YAML files.

Add vim-yaml-helper

---

vimrc

Only highlight do not remove unused java imports.
The plugin we're using doesn't seem to handle all cases and we've seen
some cases where imports have been removed when they shouldn't be. This
will bring us the benefits of seeing unused imports clearly in the
majority of cases and won't interfere with cases where they are still
being used. Maybe we can add this back when the plugin doesn't have this
bug.

Only highlight do not remove unused imports

---

vimrc

Enable the `ruby` `rubocop` linter if there's a `.rubocop.yml` file present, specify that the only linters that should run are the ones explicitly enabled, and configure the plugin so that it causes minimal visual distractions by disabling the gutter leaving a dim highlight on violations as the only visual signal of a violation.
We've got ale disabled but we're making use of `rubocop`. I and others waste time by pushing changes to a PR, waiting for tests to run, discovering rubocop violations, fixing, repushing. `rubocop` and `ale` are fast and they'd provide us with feedback immediately.
The changes also disable the gutter (the bright icons that normally display in the left bar) so that the only visual signal of violations will be blue background highlighting on the violation itself. …

Enable rubocop linting on ruby files

---

vimrc

enable puppet-lint
puppet-lint has a handful of useful linting options, we added a very
conservative whitelist to our puppet repo, so lets enable it by default.

ale: enable puppet-lint

---

vimrc.bundles

Add plugin that supports plantuml files.
We use plantuml text files for drawing diagrams and it would be helpful to see the syntax color coded and formatted in vim. Additionally the plugin will cause the vim `:make` command to generate PNGs for the file.

Add plantuml syntax plugin

---

vimrc
vimrc.bundles

Trailing whitespace, though perhaps annoying to some developers is
harmless in almost any language. Our current config highlights trailing
whitespace in red, which makes it more difficult to read documents that
happen to have trailing whitespace, or in markdown files where it is
used when grouping paragraphs.
This commit disables highlighting by default and flips the shortcut to
highlight trailing whitespace, rather than clear it.

Do not highlight trailing whitespace by default

---

vimrc.bundles

Limit the asyncomplete plugin to Java files.
There's a bug in the plugin that's been reported in
prabirshrestha/asyncomplete.vim#27 that the plugin doesn't trigger
default autocomplete behavior when the plugin isn't serving any results.
This means in non-Java files the plugin causes no results to be
displayed instead of displaying symbols available in the buffer.

Limit asyncomplete to Java files

---

vimrc

This switches text files back to the default of `textwidth=0`.
`78` is very narrow and we don't have overrides for most other file types.
This doesn't seem worth an RFC to me. 

Remove textwidth override for txt files

---

vimrc.bundles

Highlight TypeScript files using JavaScript syntax via 'leafgarland/typescript-vim'
Easier to write TypeScript without having to set syntax manually

Add TypesScript Plugin

---

README.md
python_mappings.vim
vimrc

Updates `vim-test` config to use `pytest` as the default test runner, instead of `nose`.
Also, fixes `<leader>-rl` to re-run last test in python
As far as I can tell, `pytest` is much more widely used at Braintree than `nose`

Use pytest as default python test runner, not nose

---

vimrc

Sets expandtab for Python file types
When coding in Python, my natural tendency is to hit tab to indent, but without expandtabs enabled on Python file types, vim will enter a tab character rather than 4 spaces.  This can become maddening.
I don't _think_ this should require an RFC.

sets expandtabs for python files

---

vimrc

If you use [black](https://github.com/python/black) and it's in the `Pipfile`, this will format python files on save.
Real time formatting is nice. We can't use black's vim plugin (https://github.com/python/black#vim) since our vim python is too old.

Format python files with black on save (if black is used)

---

vimrc

Configure black to use pipenv.
Since we're already checking for a Pipfile, we can tell the plugin to
run Black via pipenv. This prevents having to also install Black outside
the virtualenv.

Configure black to use pipenv

---

vimrc

For SideSearch macro, replace `| wincmd p ` with an equivalent key sequence.
There has been an issue with a terminal bell going off every time vim starts, due to the following line:
`nnoremap <Leader>ss :SideSearch <C-r><C-w><CR> | wincmd p`
The issue is that the pipe separates `wincmd` from `nnoremap` , not `:SideSearch`.  As a result `wincmd p` is run when the editing session is opened and the terminal beeps due to an error.  This is fixed by changing it to:
`nnoremap <Leader>ss :SideSearch <C-r><C-w><CR><C-w>p`
This results in the desired behavior as described by the comment on the line prior to where the macro is defined.
~~- [ ] Send RFC email to Braintree developers _if change may be impactful_. Please include a link to this PR so that discussion about the pros and cons of the …

Fix terminal bell when loading vimrc

---

vimrc

Add a shortcut for getting a GItHub URL.
This could easily just live in folks `vimrc_local` but it seems like a pretty common workflow and I'd like to increase discoverability of this plugin because I think it's v useful. Luckily too there's not much contention for the `<Leader>gX` namespace. The only other function we have mapped there is `<Leader>gw` so I don't think this would be too confusing/disruptive.

Add shortcut for getting a GitHubURL

---

vimrc

Disable style highlighting, Enable gutter indicators instead
Current linting settings make it impossible to read certain lines of
code in ruby projects. Specifically the background highlighting for
syntax issues obscures symbols in ruby.
To be more cognizant of readability concerns moving this highlighting to
the gutter should satisfy our need to mark style issues while still
allowing for developers to read the code.
Previous Behavior:
New Behavior:
~- [ ] Send RFC email to Braintree developers _if change may be impactful_. Please include a link to this PR so that discussion about the pros and cons of the change remains linked to the proposed changes. **Recent examples include**: addition of linter and completer, no longer removing end-of-line whitespace on save, changing to fzf for file …

Disable style highlighting, Enable gutter indicators instead

---

vimrc

This shows compilation errors inline and formats on save.
It makes working in elixir better.

Add mix as an ale linter and fixter

---

vimrc

Add ALE leader keys
* cool af
* helps you lint (al) and fix (af)
* helps you debug (ai)
* helps you navigate (an/aj for next ap/ak for previous)
We heavily use leader keys and adding ALE leader keys would be very helpful.
- Since this is an addition, and not impactful to current workflows, this is probably not needed.

Add ALE leader keys

---

activate.sh
config/nvim/init.vim
vimrc

This adds one compatibility if statement to not use ttymouse when in nvim and links and sets up nvim's directory for use with these dotfiles.  This should be entirely compatible with the previous usage, but just add nvim into the mix.
Why not use these dotfiles when using NeoVim?!?!

Enable dotfiles for neovim

---

vimrc.bundles

Bump the fzf and fzf.vim plugins.
The current combination of fzf and fzf.vim makes `:Tags` and
`<leader>ft` print an error instead of finding tags. Updating fzf
and fzf.vim to the latest makes it work.

Bump fzf plugins

---

vimrc

Add a ReverseLines command to reverse the lines in a file. 
This works on the entire file and also a range of lines. Command from
the vim wiki: https://vim.fandom.com/wiki/Reverse_order_of_lines
I use the long form of this quite often. One example is when looking at sumo results which are ordered most recent first.

Add a ReverseLines command to reverse the lines in a file

---

vimrc.bundles

Removes the outdated version pin for `vim-javascript`.
`vim-javascript` was pinned to a very old version. There must have been some breaking change back then, but now removing the pin doesn't break anything and gives us working highlighting with some newer JS features (notably optional chaining).
- ~Send RFC email to Braintree developers _if change may be impactful_. Please include a link to this PR so that discussion about the pros and cons of the change remains linked to the proposed changes. **Recent examples include**: addition of linter and completer, no longer removing end-of-line whitespace on save, changing to fzf for file lookup.~ change is not impactful, skipping

Remove pinned version from vim-javascript

---

vimrc

`<Leader>ds` in a vim buffer with rspec tests will now print `'specify'` and `'example'` tests
This modifies a vim shortcut which prints all rspec tests/contexts/blocks in a vim buffer. It does not currently print tests written with the `specify` or `example` methods [documented here](https://rspec.info/documentation/3.9/rspec-core/#Aliases).
Not applicable

Include all rspec tests when printing specs from vim buffer

---

vimrc.bundles

Replace deprecated puppet plugin.  The old repo suggests this new repo.
PlugInstall errors out on this old version.

Replace deprecated puppet plugin

---

vimrc

a65acc7 removed references to Inferior Slime, but missed this one.
Inferior Slime is a deprecated internal tool.

Remove missed reference to inferior slime

---

vimrc

The existing `SudoW` command provides an easy way to write a buffer if a file has accidentally been opened (and subsequently edited) with insufficient write permissions. This PR proposes some ergonomic tweaks.
* rename from `SudoW` to `W`; this is easier to remember (and type)
* quote the percent operator (which interpolates the filename) in case of spaces in the filename
* redirect `tee` output to `/dev/null` so that the buffer contents aren't re-printed

Modify sudo write command

---

dotnet_mappings.vim
vimrc

Add dotnet mappings for vim.
This allows you to run tests from dotnet files.

Add dotnet mappings

---

vimrc

Remove binding of `C-e` (`<CONTROL>` and `e`) to `lsp-document-diagnostics` for Java files.
The [default binding](http://vimdoc.sourceforge.net/htmldoc/scroll.html#CTRL-E) for `C-e` is to scroll the viewport one line at at a time.  I use this often when reading source code, however for Java files it is re-bound to a specific language server command. I currently work around this by manually making the change contained in this PR every time I create a new cpair. I'm sure this could be resolved within a `.vimrc_local` file, but I am not aware of folks using this particular language server binding, and I believe it's more likely an impediment to users used to the default binding.
I will post a link to this PR to the #talk-java Slack channel, as this will reach the most likely affected users.

Remove java binding for C-e so it can be used to scroll

---

vimrc
vimrc.bundles

Add the glaive plugin so that the autoformat plugin can be configured for other languages. See: https://github.com/google/vim-codefmt#configuring-formatters
So that we can push fewer commits that break in CI due to formatting issues.

Install glaive for autoformat configurations

---

vimrc

The PR https://github.com/braintreeps/vim_dotfiles/pull/159 causes errors when Vim is first loaded because it attempts to call `glaive#Install()` in the vimrc before the glaive plugin has been installed. This PR fixes it by only calling `glaive#Install()` if it exists.
To fix an error from appearing when vim is opened pre-`PlugInstall`.

Check for glaive before attempting to install

---

ftplugin/terraform.vim
vimrc

Enable automatically formatting `*.tfvars` files when saving in vim.
This makes it easy to get the formatting of `*.tfvars` files to match that of `*.tf` files.

Automatically format terraform *.tfvars files on save

---

vimrc

Enable spell check for got commit messages.  Also remove the `version >= 700` line as Vim 7 was released in 2006.
Prior to this change spell check was not enabled for git commit messages - now it is.

Enable spell check for git commit messages

---

vimrc.bundles

Add vim caser plugin
This plugin adds a series of shortcuts via `gs<char>` to change the case of a set of words per the documentation: https://github.com/arthurxavierx/vim-caser
This is not impactful as we are not aware of any keystrokes this would be clobbering and the functionality is helpful without being intrusive.

Add vim caser

---

vimrc

[![asciicast](https://asciinema.org/a/wQ5YIUEyN1uEiBPzGPZ1Ail8H.svg)](https://asciinema.org/a/wQ5YIUEyN1uEiBPzGPZ1Ail8H)
Remaps vim-unimpaired key bindings for `[e` and `]e` to `<C-j>` and `<C-k>`
Vim unimpaired defines `[e` and `]e` to swap the line you are on with
the previous or next line. vim-ruby-block-helpers (also installed)
redefines `]e` to mean "RubyBlockEnd", overriding the existing `]e` for
ruby files.  This change remaps the vim-unimpaired bindings to <C-j> and
<C-k> so they no longer conflict. Additionally, it re-selects when
moving selections so that you can simply repeat the move to move things
around in a file.

Remap vim-unimpaired exchange-lines commands

---

vimrc

Adds rust to the list of languages for stripping end-of-line whitespace on save.
Our team's development is heavy on rust.

Add rust to list of languages for auto-stripping whitespace on save

---

ftplugin/elixir.vim
ftplugin/puppet.vim
ftplugin/python.vim
ftplugin/ruby.vim
vimrc

Organize ALE configurations by language and include ALEFix for ruby
This sets a pattern for adding language specific configuration.  Also gives us `:ALEFix` now for ruby.

Organize ALE configurations by language and include ALEFix for ruby

---

vimrc.bundles

[![asciicast](https://asciinema.org/a/4YjMLZpfhQyEjQmzkGISMEpWh.svg)](https://asciinema.org/a/4YjMLZpfhQyEjQmzkGISMEpWh)
Add vim-gitgutter plugin.
- Provides visual feedback about the git diff in your vim gutter
- Allows you to jump between changes easily

Add vim-gitgutter

---

ruby_mappings.vim

Add `gd` shortcut to search for a tag by name.
When multiple files use the same function names, it can be hard to navigate. Using `g<C-]>` to find a tag is not that easy to do.

Add shortcut to search for tag

---

vimrc

Remap `[h` and `]h` to GitGutterPrevHunk and GitGutterNextHunk.
We have a ruby block plugin that uses [c (which is the default binding
for GitGutterPrevHunk) so this was not working as it should.

Remap ]h and [h to GitGutterNextHunk and GitGutterPrevHunk

---

ruby_mappings.vim
vimrc

Remap ]c to ]C for RubyBlockSpecParentContext
This shortcut conflicts with a builtin vim shortcut for vim-diff[1] so
it would be nice to change it to something unused.
[1]: http://vimdoc.sourceforge.net/htmldoc/diff.html#jumpto-diffs

Remap ]c to ]C for RubyBlockSpecParentContext

---

ruby_mappings.vim

Silently unmap ]c
Prevents an error message that happens when you open a second ruby file since the keybinding is already unmapped.

Silently unmap ]c

---

vimrc.bundles

[![asciicast](https://asciinema.org/a/42pjxlPvW6W7CfKYYHpOJXuiL.svg)](https://asciinema.org/a/42pjxlPvW6W7CfKYYHpOJXuiL)
Add vim-abolish plugin.
Provides handy shortcuts for coercing names to
snake/camel/underscore-case.  Also adds handy case-sensitive substitution:
```
:%S/facilit{y,ies}/building{,s}/g
```
Will substitute facility for building, facilities for buildings, and it will preserve the casing of all matches.  For example, `Facility` would become `Building`, while `facility` would become `building`.

Add vim-abolish plugin

---

vimrc.bundles

[![asciicast](https://asciinema.org/a/SWi7zdod0LGfeG3RxneFtUJXY.svg)](https://asciinema.org/a/SWi7zdod0LGfeG3RxneFtUJXY)
Add [splitjoin](https://github.com/AndrewRadev/splitjoin.vim) plugin.
- Makes it easy to swap block styles (do/end vs {})
- `gS` to split (i.e. `{}` -> `do;end`)
- `gJ` to join (i.e. `do;end` -> `{}`)

Add splitjoin plugin

---

vimrc.bundles

[![asciicast](https://asciinema.org/a/96lK1QgImmQ7GDtrwtdPpaxoF.svg)](https://asciinema.org/a/96lK1QgImmQ7GDtrwtdPpaxoF)
Add [vim-swap](https://github.com/machakann/vim-swap) plugin.
Makes it easy to swap items in an ordered list.
g<
g< swaps the item under the cursor with the former item. Moving cursor on the arg2 and pressing g<, then it swaps arg2 and the former one, arg1, to get:
call foo(arg2, arg1, arg3)
g>
g> swaps the item under the cursor with the latter item. Moving cursor on the arg2 and pressing g>, then it swaps arg2 and the latter one, arg3, to get:
call foo(arg1, arg3, arg2)
gs
gs works more interactive. It starts "swap mode", as if there was the sub-mode of vim editor. In the mode, use h/l to swap items, j/k to choose item, numbers 1 ~ 9 to select nth item, u/<C-r> to …

Add vim-swap plugin

---

vimrc.bundles

[![asciicast](https://asciinema.org/a/RQyYLHLxzq3rONUrlEUmjmDct.svg)](https://asciinema.org/a/RQyYLHLxzq3rONUrlEUmjmDct)
Add [targets.vim](https://github.com/wellle/targets.vim) plugin.
Adds text objects for arguments, parenthesis, and brackets to make it
easy to select/delete/operate on those values.
No keys, but defines several text objects:
- Pair text objects
- Quote text objects
- Separator text objects
- Argument text objects
- Tag text objects

Add targets.vim

---

vimrc.bundles

[![asciicast](https://asciinema.org/a/kBbTV1q4QDoYNLDwwXjEEKCWK.svg)](https://asciinema.org/a/kBbTV1q4QDoYNLDwwXjEEKCWK)
Add [vim-qf](https://github.com/romainl/vim-qf) plugin.
- Helps with managing the quickfix list
None that I'm aware of, but on the github page it shows a demo video suggesting that `<M-)>` works to go to the next filegroup in the quickfix list.

Add vim-qf plugin

---

vimrc.bundles

[![asciicast](https://asciinema.org/a/cbKhV2Cij1KeGNL9JDRmDrY56.svg)](https://asciinema.org/a/cbKhV2Cij1KeGNL9JDRmDrY56)
Add [tmux-complete](https://github.com/wellle/tmux-complete.vim/) plugin.
- Adds user-defined completions for words visible in other tmux panes
using `<C-X><C-S-U>`. Using this, you don't need to select + copy + paste.  Very handy when using tmux.

Add tmux-complete plugin

---

vimrc

Improve the default setup for `vim-lsp`, specifically for Java use.
By default, the `java.apply.workspaceEdit` command does not work. It must be implemented client-side, using an approach similar to the one seen [here](https://github.com/mattn/vim-lsp-settings/blob/458de9338638417ded27d3e7a8798e122d0abf71/settings/eclipse-jdt-ls.vim). It also adds the recommended setup approach shown in vim-lsp's [README](https://github.com/prabirshrestha/vim-lsp#registering-servers).

Improve default vim-lsp setup

---

vimrc

This PR simply enables LSP diagnostic echoing, which shows the error at the bottom of the window when the cursor hovers over one. Without this, it is unclear what the problem is.

Enable LSP diagnostic echo

---

vimrc

Apparently the log configuration for `vim-lsp` causes issues for some people ([link](https://github.com/braintreeps/vim_dotfiles/pull/179#issuecomment-732252196)), so this PR removes those two lines because they're not really needed by default.

Remove vim-lsp log lines by default

---

dotnet_mappings.vim

Update the default dotnet framework version.
This is required to run tests against the current SDK version.

Update default dotnet framework version

---

javascript_mappings.vim
vimrc

This enables running mocha tests in the node SDK (requires a small
change to the SDK as well).
It is convenient to be able to run tests with `\rf`.

Add javascript vim-test mappings

---

vimrc.bundles

Add vim-signature plugin.
It makes marks visible in the gutter, which makes it easier to use them
for navigation.
It does not conflict with other plugins that use the gutter (see screenshot -- you can still see git diffs in the gutter, for example.)

Add vim-signature plugin

---

ftplugin/go.vim
vimrc
vimrc.bundles

1. Shortcuts for golang tests.
2. Removing `maralla/completor.vim`
3. Registering the golang language server.
1. `\rf` is a lot faster than switching panes and typing `go test -run 'TestMyFunction' `
2. This plugin has been causing some kind of panic, and inserting it as the only result in completion drop-downs: 
I was unable to get it into a working state. Using `vim-go` gives us helpful auto-completion via `<C-x><C-o>`
3. This gives us a lot of nice features, including all of the same shortcuts we already use for Java (rename, jump to definition/implementation, find references, etc.): https://github.com/braintreeps/vim_dotfiles/blob/8b67b36cfaa74ca9c3974364caea507a11e5d55c/vimrc#L255-L270

Golang Shortcuts & Language Server

---

dotnet_mappings.vim
ftplugin/elixir.vim
java_mappings.vim
javascript_mappings.vim
python_mappings.vim
ruby_mappings.vim
vimrc

Remove extraneous `space` character from compound/multi-line mappings to avoid side-effects.
Invoking a mapping (eg: `\rf`) includes a `space` between the `:wa<CR>` and `:TestNearest<CR>`.
For those who do not remap the `space` key, this simply moves the cursor one character to the right; this may not be a huge deal, but it's also not expected.
For those who do remap the `space` key, it activates that mapping which is not desirable.
I have not sent an RFC email as I don't think this is an impactful change, but I am open to doing so if people think otherwise.

Remove extraneous `space` character from compound/multi-line mappings to avoid side-effects.

---

ftplugin/sh.vim

Prior to this commit we did not enable any linters for bash & sh. This
commit enables the shellcheck linter, https://www.shellcheck.net.
Using shellcheck when writing bash code has proven to be extremely
helpful. It outputs clear messages which are augmented by a very helpful
wiki. Each linter warning includes a specific code which makes it
extremely easy to google for, e.g. SC2086. The wiki pages also are a
great resource for learning about bash and understanding why the linter
flagged a particular construct, see the SC2086 wiki page as an example,
https://github.com/koalaman/shellcheck/wiki/SC2086. It has in my
experience one of the best workflows for linting code.
I discussed adding shellcheck to our dotfiles previously, but @pgr0ss
was rightfully concerned about all the noise for …

enable shellcheck to lint bash & sh files

---

README.md

Fix the shortcut for running the last vimux command to `\vl`
It currently shows the command to run the last test, not vimux command.

Fix command for run last vimux in README

---

config/nvim/init.vim
vimrc
vimrc.bundles

Neovim 0.5 has support for native LSP. This PR detects when the user is running Neovim 0.5, and configures the editor's native LSP over `vim-lsp`.
So that users interested in using Neovim's native LSP support can do so.

Add support for Neovim-native LSP

---

config/nvim/init.vim
vimrc.bundles

This PR adds support for [treesitter](https://github.com/nvim-treesitter/nvim-treesitter#nvim-treesitter) to users of Neovim 0.5.
Treesitter offers improved syntax highlighting, folding, and buffer intelligence on which other tools can be built

Add treesitter support

---

vimrc

This allows per system, instead of just per user overrides.
If, for example, you want to allow your users to have specific personal overrides, but still don't want to store it in the global vim_dotfiles repo, you can now put them in /etc/vim/vimrc.global!
~- [ ] Send RFC email to Braintree developers _if change may be impactful_. Please include a link to this PR so that discussion about the pros and cons of the change remains linked to the proposed changes. **Recent examples include**: addition of linter and completer, no longer removing end-of-line whitespace on save, changing to fzf for file lookup.~
Additive change.

Add Global Overrides file in /etc/vim/vimrc.global

---

ftplugin/markdown.vim
vimrc
vimrc.bundles

Prior to this commit we were using 'jtratner/vim-flavored-markdown' to
augment the builtin highlighter, however it has some annoying bugs,
especially with [markdown lists](https://github.com/jtratner/vim-flavored-markdown/issues/24). It also appears to be a dead project.
So switch to vim's builtin highlighter whose development is maintained
by [tpope](https://github.com/tpope/vim-markdown) and configure the set of highlighters for fenced code blocks in 
addition.
Also remove 'plasticboy/vim-markdown' which offers similar features, but
I didn't see a compelling reason to use it versus the built in
highlighter.

Switch markdown syntax highlighter to vim's

---

config/nvim/init.vim

Add `java-test` server extension jars to the bundle list when initializing the `jdtls` language server.
This extension provides support for several new LSP commands that make it possible to discover and run Java tests.

Initialize jdtls language server with java-test extension

---

ftplugin/markdown.vim

Using multiple syntax highlighters at the same time can cause problems.
Java's syntax highlighting breaks spell check, which is nice to have in
markdown files, so remove it, see
https://github.com/tpope/vim-markdown/issues/89 for more info.

java: remove from markdown fenced languages

---

vimrc.bundles

Pin `nvim-treesitter` to the `0.5-compat` branch.
This branch is recommended for users of 0.5, which should be the
standard for a while.
See:
https://github.com/nvim-treesitter/nvim-treesitter/commit/20b5dd9893e1e7bc450dbed74d116123bb0ba2e3

Pin nvim-treesitter to 0.5-compat branch

---

vimrc

Initialize the `vim-lsp` plugin with the `java-test` extension bundles. This mimics the [existing configuration](https://github.com/braintreeps/vim_dotfiles/blob/fe210b3984f4bd438dc74bd9871edd2f760d4fcb/config/nvim/init.vim#L71-L79) of Neovim 0.5's native LSP client, but is compatible with Vim and Neovim < 0.5.
So that the extension is available to users of Vim and Neovim < 0.5.

Add java-test extension bundles to vim-lsp initialization

---

ftplugin/markdown.vim

This adds pandoc as a fixer for markdown files, formatting them with
pandoc. I find this to greatly increase the ease of composing markdown
in vim as lines are broken by pandoc at 72 and it is easier to spot
errors since pandoc will format based on its parsing of the document.

markdown: auto format markdown files with pandoc

---

vimrc
vimrc.bundles

Adds the [vim-easy-align](https://github.com/junegunn/vim-easy-align) plugin and binds both the generic commands as well as some ones specifically for GHE-flavored markdown tables.
The first two binds are from the vim-easy-align README. The second two binds are from this helpful blog post: https://calebeby.gitlab.io/blog/2016/formatting-markdown-tables-in-vim/
This makes auto-formatting markdown tables a breeze.

Add vim-easy-align, and bind extra GHE-flavored markdown table commands

---

vimrc

Prior to this commit bash & sh files were not formatted automatically.
This commit formats those files on save with shfmt. The format can be
viewed here,
https://github.com/mvdan/sh/blob/master/syntax/canonical.sh. Notably
shfmt uses tabs by default rather than spaces. This commit also provides
the ability to disable the functionality per repo by touching
.shfmt_disable.
Manually formatting source code is tedious, error prone, and
inconsistent between people. Go has demonstrated that removing
formatting as a manual task provides more space for a person to
concentrate on program logic.
This functionality is enabled by default so that formatting is enforced
everywhere, but you can disable it if needed on a repo.
In my experience shfmt does a good job of formatting bash & sh files,
also the …

enable shfmt to auto format bash & sh files by default

---

vimrc

Configure the `vim-test` plugin for Gradle-based Java projects.
So that the standard test-runner shortcuts work as expected for Gradle projects.

Configure Java test runner for Gradle projects

---

config/nvim/init.vim
vimrc.bundles

Install [Telescope](https://github.com/nvim-telescope/telescope.nvim) for users of Neovim 0.5, and configure LSP commands to use Telescope pickers where available.
Neovim LSP's default behavior for some tasks, notably running code actions, is not great. It uses the default Vim input mechanism, which provides a long list of items, and prompts for a number. `fzf-lsp.nvim` was installed in order to make that experience better, but recently it has not been working, presumably due to some updates that broke behavior. Telescope is a functional alternative that provides a much more usable, searchable list for code actions and other tasks.
In addition to being useful for users of LSP, Telescope has many other features as well, providing a lot of options for those who want to take full advantage …

Add telescope when using Neovim 0.5

---

vimrc.bundles

This adds `vim-rake` to introduce commands like `:A`, `:AS`, `:AV`, etc. for Ruby codebases that are not Rails apps, allowing developers to quickly navigate to corresponding spec files. This still requires adding a `.projections.json` file to your app to specify the alternate file pattern. See [tpope/vim-projectionist#alternate-files](https://github.com/tpope/vim-projectionist#alternate-files) for an example of a `.projections.json` file.
Limiting the `vim-projectionist` plugin disallows the `.projections.json` file from affecting Ruby codebases that are not Rails applications. Adding `vim-rake` is recommended in [the vim-rails FAQ](https://github.com/tpope/vim-rails#faq) when needing something for non-Rails codebases.

Add vim-rake and use vim-projectionist for all file types

---

.gitmodules
README.md
tmux_example.conf

These are a bunch of changes that I've been working on for the tmux.conf. Improvements include:
`ctrl-a-|` and `ctrl-a-_` to open a new pane all the way to the left or all the way to the bottom.
`` ctrl-a-` `` to open a quake-tmux in newer tmux versions.
`ctrl-a-ctrl-d` to disconnect all other connections besides the current one.
`ctrl-y` add back synchronize panes with prompt, but don't prompt on unsynchronize.
Pass `SSH_AUTH_SOCK ` on to tmux.  This is now more important than the previous `SSH_*` variables.
Change cpair.conf to a more generic include for a local and a global tmux.

Add ranmason improvements

---

vimrc
vimrc.bundles

e.g. If you have a query like this:
SELECT ma.token
FROM merchant_accounts ma
WHERE merchant_fk = ${merchant_pk};
and you run the crosspaste function (with \qp "query paste"
shortcut), Vim will prompt for a merchant_pk. If you type "1066",
it will then paste
SELECT ma.token
FROM merchant_accounts ma
WHERE merchant_fk = 1066;
Added plugin to vimrc_bundles. Added shortcut to vimrc.
Added easy paste to make it easy to run saved queries in vim.

Adding plugin vim-crosspaste

---

README.md
vimrc

Fixed a mistake in a method name (as I made the plugin, I changed the method name from CrossQuery to CrossPaste, and the vimrc I pushed had
the old method name). I also added a line in the README to explain the mapping.
_Example: Specify full path when running focused specs._
It was a mistake. It didn't touch any existing fuctionality, but it didn't allow the new feature, so I'm fixing it.
_Example: When only a relative path is specified, focused specs don't run if the shell's current working directory differs from the project root._

Fixed method call in map. Added mapping to README.

---

vimrc

Changes the default config for the shell script formatter to use tabs rather than spaces
It was explained when shfmt was added to this repo that shfmt uses tabs, but it turns out there was a feature added to shfmt to permit spaces, so this would be a more natural default for .sh files.
I routinely end up having to fix PRs that got tab-ified, so this is a real time saver.
- [*] Send RFC email to Braintree developers (via slack)

shfmt supports spaces, so let's avoid tabs

---

vimrc

This adds two new shortcuts to the setup.  Both of them are for my vim-crosspaste plugin. One of them is
**\qb** _query block_ this takes the selected text and pastes it across TMUX panes, doing pattern substitutions the way crosspaste does. This is different from standard crosspaste that picks the text around the cursor, going back to a blank space and forward to a semicolon.
**\qq** _quick query_ this does the same thing as a standard query, but it assumes last entered information rather than prompting. e.g. If you crosspaste text with ${foo} and you've already entered "bar" as a _foo_ in a previous paste, \qq would automatically replace ${foo} instead of prompting with a default of "bar".
_Example: Specify full path when running focused specs._
\qb is more similar to how some people …

Added shortcuts for vim-crosspaste commands to paste a block or

---

vimrc.bundles

See title.
This avoids warnings every time vim starts on older versions of vim and future breaking changes.

Pin vim-go to latest release

---

vimrc

When searching for files in Vim I don't remember needing to respect case, and, at least in our Ruby projects, the files are default lower case anyway. Changing from the default "smart case" (which uses case insensitive matching when the input is all lower case and case sensitive matching when at least one uppercase letter is present) to to case insensitive matching always means that searching for a Ruby class name like MyClass will match my_class.rb, which seems like a usability win when copy/pasting from code.
Note: discussed internally with poll on behavior change.

Default to case-insensitive fzf

---

vimrc.bundles

`vim-ruby` was pegged to a commit from 2018, it's been updated a bunch since then and I believe we can safely adopt the newer versions.  This commit un-pegs the plugin from the specified commit.
Newer versions of `vim-ruby` have improvements but also allows to match certain rubocop rules better, eg: https://github.com/vim-ruby/vim-ruby/blob/master/doc/ft-ruby-indent.txt#L112 is a change that's not included in the version we were using but fixes some indentation issues.
Screen recording that shows basic ruby working after updating the plugin:

Un-pegging vim-ruby to a very old commit

---

ftplugin/markdown.vim

Reverts braintreeps/vim_dotfiles#199
After asking around, it seems a lot of people share at least some of my sentiments on this:
* This fixer doesn't "kick in" consistently; markdown files in vim will seemingly randomly suddenly start getting formatted by this. Having to know how to invoke the fixer manually is annoying extra cognitive burden of which the A in ALE is supposed to relieve us, yet it's not holding up that end of the bargain.
* Once the fixer _does_ "kick in", it can't be fought against, to the point where changing a single line in a readme suddenly becomes a 300+ line change for no good reason. This leads to people making separate PRs just to apply the formatting, then a PR on top of that to actually make the desired change.
* The formatting is aesthetically displeasing, …

Revert "markdown: auto format markdown files with pandoc"

---

vimrc

Ignore .rbi files while fuzzy-finding, yet do not .gitignore them.
.rbi files are autogenerated by Sorbet and disrupt fuzzy-finding.

*.rbi files are generated by the sorbet gem and can be ignored

---

vimrc

Moving these bindings above the system and local overrides allows them to be overridden by these overrides. Otherwise there is no sensible way to deviate from these key bindings.
Original commit: 4b3bba2
Move window navigation bindings above the system and local overrides.
Moving these bindings above the system and local overrides allows them to be overridden by these overrides. Otherwise there is no sensible way to deviate from these key bindings.
Original commit adding bindings: 4b3bba2

Move window navigation bindings

---

vimrc.bundles

Fix airblade/vim-gitgutter Plugin updates
Without specifying the "main" branch, vim-plug tries to update from the non-existent "master" branch.
```
x vim-gitgutter:
fatal: invalid reference: master
```
Similar to:
```
Plug 'cespare/vim-toml', {'branch': 'main'}
```
Plugin github link: https://github.com/airblade/vim-gitgutter

Fix airblade/vim-gitgutter Plugin updates

---

vimrc
vimrc.bundles

Add the plugin, disable it, and add a toggle.
This adds the official vim copilot integration, `copilot.vim`.
This plugin is basically just autocompletions for now. They should not be enabled by default.
To get started, pull and `:Copilot setup`
We want to provide options for using GenAI at Braintree without disrupting existing workflows.

Add copilot.vim, disabled by default with a toggle

---

vimrc

Dont clear and echo before running test commands with vim-test such as `\rf`
Before:
`\rf`
`clear; echo "bundle exec rspec spec/foo/bar_spec.rb:152"; bundle exec rspec spec/foo/bar_spec:152`
After:
`\rf`
`bundle exec rspec spec/foo/bar_spec:152`
- Clearing the screen is not very helpful, many times I want to see the failures that had occured in runs prior and other details.
- The echo statement is actually confusing because sometimes you may start out with an \rf which would output
* echo "bundle exec rspec spec/foo/bar_spec.rb:152"; bundle exec rspec spec/foo/bar_spec.rb:152"
* Many times I want to just re-run the spec file with a different line number, you may just manually re-run the last command and change the last line `152` to something else and then your pair will be like "huh …

Dont clear and echo before running test commands with vim-test
